apiVersion: v1
kind: Template
labels:
  app: jenkins-agents
metadata:
  annotations:
    description: Jenkins agents images
    iconClass: icon-jenkins
    openshift.io/display-name: Jenkins
    openshift.io/documentation-url: https://docs.openshift.org/latest/using_images/other_images/jenkins.html
    openshift.io/long-description: This template builds a set of Jenkins agents images.
    tags: jenkins
  name: jenkins-agents
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-agent-node-sonar
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Jenkins Agent - NodeJS 8 & Sonar-Runner 2.4
    name: jenkins-agent-node-sonar
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-node-sonar:${JENKINS_NODE_REF}
    resources:
      limits:
        cpu: 200m
        memory: 768Mi
    source:
      contextDir: ${JENKINS_NODE_CONTEXT}
      git:
        uri: ${JENKINS_NODE_GIT}
        ref: "${JENKINS_NODE_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: false
    triggers:
    - type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-agent-debian
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Jenkins Agent - Debian
    name: jenkins-agent-debian
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-debian:${JENKINS_DEBIAN_REF}
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    source:
      contextDir: ${JENKINS_DEBIAN_CONTEXT}
      git:
        uri: ${JENKINS_DEBIAN_GIT}
        ref: "${JENKINS_DEBIAN_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: false
    triggers:
    - type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-agent-centos
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Jenkins Agent - CentOS
    name: jenkins-agent-centos
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-centos:${JENKINS_CENTOS_REF}
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    source:
      contextDir: ${JENKINS_CENTOS_CONTEXT}
      git:
        uri: ${JENKINS_CENTOS_GIT}
        ref: "${JENKINS_CENTOS_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: false
    triggers:
    - type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-agent-klar
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Jenkins Agent - Klar
    name: jenkins-agent-klar
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-klar:${JENKINS_KLAR_REF}
    resources:
      limits:
        cpu: 200m
        memory: 768Mi
    source:
      contextDir: ${JENKINS_KLAR_CONTEXT}
      git:
        uri: ${JENKINS_KLAR_GIT}
        ref: "${JENKINS_KLAR_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: false
    triggers:
    - type: ImageChange
    - type: ConfigChange
parameters:
- description: Jenkins NodeJS Agent Dockerfile Root Directory
  displayName: Jenkins NodeJS Agent ContextDir
  name: JENKINS_NODE_CONTEXT
  value: /jenkins-agent-node-sonar
- description: Jenkins NodeJS Agent Repository
  displayName: Jenkins NodeJS Agent Repository
  name: JENKINS_NODE_GIT
  value: https://github.com/faust64/docker-jenkins
- description: Jenkins NodeJS Agent Repository Branch, Tag or Commit hash
  displayName: Jenkins NodeJS Agent Repository Ref
  name: JENKINS_NODE_REF
  value: master
- description: Jenkins Debian Agent Dockerfile Root Directory
  displayName: Jenkins Debian Agent ContextDir
  name: JENKINS_DEBIAN_CONTEXT
  value: /jenkins-agent-debian
- description: Jenkins Debian Agent Repository
  displayName: Jenkins Debian Agent Repository
  name: JENKINS_DEBIAN_GIT
  value: https://github.com/faust64/docker-jenkins
- description: Jenkins Debian Agent Repository Branch, Tag or Commit hash
  displayName: Jenkins Debian Agent Repository Ref
  name: JENKINS_DEBIAN_REF
  value: master
- description: Jenkins CentOS Agent Dockerfile Root Directory
  displayName: Jenkins CentOS Agent ContextDir
  name: JENKINS_CENTOS_CONTEXT
  value: /jenkins-agent-centos
- description: Jenkins CentOS Agent Repository
  displayName: Jenkins CentOS Agent Repository
  name: JENKINS_CENTOS_GIT
  value: https://github.com/faust64/docker-jenkins
- description: Jenkins CentOS Agent Repository Branch, Tag or Commit hash
  displayName: Jenkins CentOS Agent Repository Ref
  name: JENKINS_CENTOS_REF
  value: master
- description: Jenkins Klar Agent Dockerfile Root Directory
  displayName: Jenkins Klar Agent ContextDir
  name: JENKINS_KLAR_CONTEXT
  value: /jenkins-agent-klar
- description: Jenkins Klar Agent Repository
  displayName: Jenkins Klar Agent Repository
  name: JENKINS_KLAR_GIT
  value: https://github.com/faust64/docker-jenkins
- description: Jenkins Klar Agent Repository Branch, Tag or Commit hash
  displayName: Jenkins Klar Agent Repository Ref
  name: JENKINS_KLAR_REF
  value: master
